In [ ]:
from sklearn.datasets import make_classification # Import the make_classification function from sklearn.datasets to create a synthetic dataset.
import torch # Import the PyTorch library, which is essential for building and training neural networks.

In [ ]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples (data points) to generate
    n_features=2,       # Number of features (input variables) for each sample
    n_informative=2,    # Number of informative features, which are useful for classification
    n_redundant=0,      # Number of redundant features, which are linear combinations of informative features
    n_classes=2,        # Number of target classes (e.g., binary classification with 0 and 1)
    random_state=42     # Seed for reproducibility, ensuring the same dataset is generated each time
)

In [ ]:
X # Display the features (input data) of the generated dataset.

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X.shape # Display the shape (dimensions) of the features array (number of samples, number of features).

(10, 2)

In [ ]:
y # Display the target labels (output data) of the generated dataset.

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
y.shape # Display the shape (dimensions) of the labels array (number of samples).

(10,)

In [ ]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32) # Convert the NumPy array X to a PyTorch tensor with float32 data type.
y = torch.tensor(y, dtype=torch.long) # Convert the NumPy array y to a PyTorch tensor with long (integer) data type, suitable for class labels.

In [ ]:
X # Display the PyTorch tensor X, which now holds the features.

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y # Display the PyTorch tensor y, which now holds the labels.

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import Dataset, DataLoader # Import Dataset and DataLoader from torch.utils.data to create custom datasets and handle data loading in batches.

In [ ]:
class CustomDataset(Dataset):
  # Define a custom dataset class that inherits from torch.utils.data.Dataset.
  # This class provides an interface for accessing data samples.

  def __init__(self, features, labels):
    # Constructor method to initialize the dataset with features and labels.
    self.features = features # Store the input features.
    self.labels = labels     # Store the corresponding labels.

  def __len__(self):
    # Returns the total number of samples in the dataset.
    return self.features.shape[0] # The number of samples is the first dimension of the features tensor.

  def __getitem__(self, index):
    # Retrieves a single sample and its label at the given index.
    return self.features[index], self.labels[index] # Return the feature and label for the specified index.

In [ ]:
dataset = CustomDataset(X, y) # Create an instance of the CustomDataset using the PyTorch tensors X (features) and y (labels).

In [ ]:
len(dataset) # Get the total number of samples in the dataset using the __len__ method.

10

In [ ]:
dataset[2] # Access the third sample (index 2) from the dataset, which calls the __getitem__ method.

(tensor([-2.8954,  1.9769]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False) # Create a DataLoader instance from the custom dataset.
# batch_size=2: Specifies that data will be loaded in batches of 2 samples.
# shuffle=False: Data will not be shuffled, so samples are loaded in their original order.

In [ ]:
for batch_features, batch_labels in dataloader:
  # Iterate through the DataLoader, which yields batches of features and labels.
  print(batch_features) # Print the features tensor for the current batch.
  print(batch_labels)   # Print the labels tensor for the current batch.
  print("-"*50)       # Print a separator line for better readability between batches.

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
